
# version: 2

# models:
#     - name:   
#       description: "A starter dbt model"
#       columns:
#           - name: id
#             description: "The primary key for this table"
#             tests:
#                 - unique
#                 - not_null

#     - name: dbt_training_project
#       description: "A starter dbt model"
#       columns:
#           - name: id
#             description: "The primary key for this table"
#             tests:
#                 - unique
#                 - not_null
version: 2
sources:
  - name: STAGE
    description: This is RAW_TEST Database Source Tables used for creating STANDARD_TEST Layer
    database: PC_MATILLION_DB
    tables:
      - name: CUSTOMER
      - name: ORDERS
